version: "3.9"
   
services:
  db-order:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
  order-api:
    container_name: order-api
    build: ./Order-Api/
    command: python ./Order-Api/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8080:8000"
    depends_on:
      - db-order